### ISSUE TITLE
取不到loading的值

### ISSUE THREAD

**Issue by chunbin1** [niqingyang/mobx-loading#1]
示例：
https://codesandbox.io/s/morning-water-x64bn?fontsize=14

**Comment by niqingyang** [comment]
```diff
export default inject(({ countStore, loading }) => ({
  count: countStore.count,
  add: countStore.add,
  add5s: countStore.add5s,
  minus: countStore.minus,
-  loading: loading.actions["addaf"]
+  loading: loading.models["addaf"]
}))(BrotherTest);
```

```js
@loading("addaf") // 其实是在 loadingStore 的 models 属性中创建了一个状态
```

建议直接写成

```diff
// 然后可以通过 loadingStore.models.AddStore 获取模型的状态
// 通过 loadingStore.actions['AddStore/add5s'] 获取函数的执行状态
- @loading("addaf")
+ @loading
  @action
  add5s = () => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        this.count++;
        resolve();
      }, 5000);
    });
  };
}
```

可以参考文档：[https://acme.top/mobx-react-stores-doc](https://acme.top/mobx-react-stores-doc) 中的 `监听加载状态`

**Comment by chunbin1** [comment]
谢谢~ 话说mobx-react-stores不开源吗

**Comment by chunbin1** [comment]
还有一个问题
示例：https://codesandbox.io/s/morning-water-x64bn?fontsize=14
第一加载的时候 loading为undefined 只有按一次才会loadingStore.actions中才会有''AddStore/add5s''

**Comment by niqingyang** [comment]
是打算开源的，用 mobx-react-stores 重写的 antd pro 也打算开源，但是目前还有些待开发的功能没完善好呢，而且公司内部在用 mobx-react-stores 时还没有完成任何一个项目呢，所以不合适放出来，担心会比较坑

**Comment by niqingyang** [comment]
设计如此，因为参考了 dva 的 loading 逻辑，dva 也是这样的，我在做 antd pro 的时候看到他们调用为了避免 undefined，采用的写法是获取状态时加两个 `!`，例如：!!loading.actions['XXX/XXX']
```js
export default inject(({ countStore, loading }) => ({
  count: countStore.count,
  add: countStore.add,
  add5s: countStore.add5s,
  minus: countStore.minus,
-  loading: loading.actions["addaf"]
+  loading: !!loading.models["addaf"]
}))(BrotherTest);
```

**Comment by chunbin1** [comment]
还真是这样，以前用的时候一般都是在componentDidmount执行异步操作，所以有一瞬间 loading为undefined并没有察觉到，还以为默认是false的，谢谢大佬🙏
